#!/bin/sh

# this is file '/usr/sbin/apache2ctl' from 'apache2' package.

ARGV="$@"
if test -z "$APACHE_CONFDIR" ; then
    if test "${0##*apache2ctl-}" != "$0" ; then
	APACHE_CONFDIR="/etc/apache2-${0##*apache2ctl-}"
    else
	APACHE_CONFDIR=/etc/apache2
    fi
fi

test -z "$APACHE_ENVVARS" && APACHE_ENVVARS="$APACHE_CONFDIR/envvars"
if test -f $APACHE_ENVVARS; then
  . $APACHE_ENVVARS
fi

if test "$APACHE_CONFDIR" != /etc/apache2 ; then
    APACHE_ARGUMENTS="-d $APACHE_CONFDIR $APACHE_ARGUMENTS"
fi

HTTPD=${APACHE_HTTPD:-/usr/sbin/apache2}
LYNX="${APACHE_LYNX:-www-browser -dump}"
STATUSURL="${APACHE_STATUSURL:-http://localhost:80/server-status}"
ULIMIT_MAX_FILES="${APACHE_ULIMIT_MAX_FILES:-ulimit -n 8192}"

# Set the maximum number of file descriptors allowed per child process.
if [ "x$ULIMIT_MAX_FILES" != "x" ] ; then
    $ULIMIT_MAX_FILES
fi

ERROR=0
if [ "x$ARGV" = "x" ] || [ "x$ARGV" = "xusage" ] || [ "x$ARGV" = "xhelp" ] || [ "x$ARGV" = "x--help" ]; then 
    echo "Usage: $0 start|stop|restart|graceful|graceful-stop|configtest|status|fullstatus|help" >&2
    echo "       $0 <apache2 args>" >&2
    echo "       $0 -h            (for help on <apache2 args>)" >&2
    exit 1
fi

get_status () {
    if ! $LYNX $STATUSURL ; then
        echo "'$LYNX $STATUSURL'" failed. >&2
        echo Maybe you need to install a package providing www-browser or you >&2
        echo need to adjust the APACHE_LYNX variable in /etc/apache2/envvars >&2
        exit 1
    fi
}

mkdir_chown () {
    local O
    WNER="$1"
    local DIR="$2"
    local STAT="$(LC_ALL=C stat -c %F:%U $DIR 2> /dev/null || true)"
    if [ "$STAT" = "" ] ; then
        local TMPNAME=$(mktemp -d $DIR.XXXXXXXXXX) || exit 1
        chmod 755 $TMPNAME || exit 1
        chown $OWNER $TMPNAME || exit 1
        if ! mv -T $TMPNAME $DIR 2> /dev/null; then
            rmdir $TMPNAME
            # check for race with other apachectl
            if [ "$(LC_ALL=C stat -c %F:%U $DIR 2>/dev/null)" != "directory:$OWNER" ]
            then
                echo Cannot create $DIR with owner $OWNER.
                echo Please fix manually. Aborting.
                exit 1
            fi
        fi
    elif [ "$STAT" != "directory:$OWNER" ] ; then
        echo $DIR already exists but is not a directory owned by $OWNER.
        echo Please fix manually. Aborting.
        exit 1
    fi
}

case $ARGV in
    start)
	mkdir -p ${APACHE_RUN_DIR:-/var/run/apache2}
	mkdir_chown ${APACHE_RUN_USER:-www-data} ${APACHE_LOCK_DIR:-/var/lock/apache2}
        # ssl_scache shouldn't be here if we're just starting up.
        # (this is bad if there are several apache2 instances running)
	rm -f ${APACHE_RUN_DIR:-/var/run/apache2}/*ssl_scache*
	$HTTPD ${APACHE_ARGUMENTS} -k $ARGV
	ERROR=$?
	;;
    stop|graceful-stop)
	$HTTPD ${APACHE_ARGUMENTS} -k $ARGV
	ERROR=$?
	;;
    restart|graceful)
	if $HTTPD ${APACHE_ARGUMENTS} -t 2> /dev/null ; then
            $HTTPD ${APACHE_ARGUMENTS} -k $ARGV
	else
            $HTTPD ${APACHE_ARGUMENTS} -t
	fi
	ERROR=$?
	;;
    startssl|sslstart|start-SSL)
	echo The startssl option is no longer supported.
	echo Please edit httpd.conf to include the SSL configuration settings
	echo and then use "apachectl start".
	ERROR=2
	;;
    configtest)
	$HTTPD ${APACHE_ARGUMENTS} -t
	ERROR=$?
	;;
    status)
	get_status | awk ' /process$/ { print; exit } { print } '
	;;
    fullstatus)
	get_status
	;;
    *)
	$HTTPD ${APACHE_ARGUMENTS} $ARGV
	ERROR=$?
esac

if [ "$ERROR" != 0 ] ; then
    echo Action \'"$@"\' failed.
    echo The Apache error log may have more information.
fi
exit $ERROR
